server:
  port: 8081

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.it.myapp.entity

#showSql
logging:
  level:
    com:
      it:
        myapp:
          mapper : debug